version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Pre-build steps...."
      - echo "Zipping deployment Packages..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py mock_data_generator.py upload_to_s3.py
  post_build:
    commands:
      - echo "Uploading to s3...."
      - aws s3 cp deployment_package.zip s3://ecomm-lambda-builds-zip/
      - echo "Updating Lambda function via s3...."
      - aws lambda update-function-code --function-name ecom-data-pipeline --s3-bucket ecomm-lambda-builds-zip --s3-key deployment_package.zip
      - echo "Deployment completed!!!"
